apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticpage-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staticpage-operator
  template:
    metadata:
      labels:
        app: staticpage-operator
    spec:
      serviceAccountName: staticpage-operator
      containers:
      - name: operator
        image: 01bit/operatore:v3