apiVersion: v1
kind: ServiceAccount
metadata:
  name: staticpage-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: staticpage-operator
rules:
- apiGroups: ["example.com"]
  resources: ["staticpages"]
  verbs: ["*"]
- apiGroups: ["", "apps", "v1"]
  resources: ["deployments", "services", "configmaps"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: staticpage-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: staticpage-operator
subjects:
- kind: ServiceAccount
  name: staticpage-operator
  namespace: default