apiVersion: v1
kind: Pod
metadata:
  name: s3-example
spec:
  containers:
  - name: app
    image: busybox
    command: [ "sh", "-c", "while true; do echo hello; sleep 10;done" ]
    volumeMounts:
    - mountPath: "/data"
      name: s3-volume
  volumes:
  - name: s3-volume
    persistentVolumeClaim:
      claimName: my-pvc
