apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
  # Namespace depends on the configuration in the storageclass.yaml
  namespace: kube-system
stringData:
  accessKeyID: "Slpn9oyh1WRvu6LfhJwx"
  secretAccessKey: "01ETmvTmXUpn1xqSJdykO3Wrcpbjrn8TsHCPmKrn"
  # For AWS set it to "https://s3.<region>.amazonaws.com"
  endpoint: "http://192.168.1.99:9000"
  # If not on S3, set it to ""
  region: "eu-1"