apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
  
data:
  fluent.conf: |
    <source>
      @type dummy
      @id dummy_input
      tag logstash
      rate 1
      dummy {"message":"test log message", "@timestamp":"${time}"}
    </source>

    <filter logstash>
      @type record_transformer
      <record>
        @timestamp ${time}
      </record>
    </filter>

    <match logstash>
      @type elasticsearch
      @id out_es
      host elasticsearch-logging.kube-system.svc.cluster.local
      port 9200
      logstash_format true
      logstash_prefix test-logs
      flush_interval 5s
    </match>
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.18.0-debian-elasticsearch7-1.2
        env:
          - name: FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch-logging.kube-system.svc.cluster.local"
          - name: FLUENT_ELASTICSEARCH_PORT
            value: "9200"
        volumeMounts:
          - name: config-volume
            mountPath: /fluentd/etc/
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: fluentd-config
