apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-service-test
  labels:
    app: jwt-app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-app-test
  template:
    metadata:
      labels:
        app: jwt-app-test
    spec:
      containers:
      - name: app-jwt-container
        image: 01bit/jwt-service:v2  
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: jwt-service-test
spec:
  selector:
    app: jwt-app-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: "jwt-example"
  namespace: default  # Aggiungi il namespace corretto qui
spec:
  selector:
    matchLabels:
      app: jwt-service-test
  jwtRules:
  - issuer: "example.com"
    jwksUri: "http://jwt-issuer.default.svc.cluster.local/.well-known/jwks.json"

---