version: '3.8'

services:

    # OpenTelemetry Collector
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4318:4318"  # OTLP HTTP
      - "9464:9464"  # Prometheus exporter
  todo:
    build: 
      context: .
      dockerfile: dockerfile.todo-service
    volumes:
      - .:/usr/src/app:rw
    ports:
      - 8081:8080
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4318
      #- OTEL_LOG_LEVEL=DEBUG
    depends_on:
      - collector
  auth:
    build: 
      context: .
      dockerfile: dockerfile.auth-service
    volumes:
      - .:/usr/src/app:rw
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  jaeger:
    image: jaegertracing/all-in-one
    ports:
        - 4318
        - 16686:16686
    environment:
        COLLECTOR_OTLP_ENABLED: true
  prometheus:
      image: prom/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      volumes:
        - ./prometheus/:/etc/prometheus/
      ports:
        - 9090:9090
