apiVersion: v1
kind: Pod
metadata:
  name: skaffold-demo
  labels:
    app: skaffold-demo
spec:
  containers:
  - name: skaffold-demo
    image: 01bit/skaffold-demo
---
apiVersion: v1
kind: Service
metadata:
  name: skaffold-demo
spec:
  selector:
    app: skaffold-demo
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000  # Puoi scegliere un numero di porta compreso tra 30000 e 32767

