apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-demo
  namespace: flux-system
spec:
  interval: 5m
  path: ./manifests  # Aggiorna il percorso corretto
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-demo-repo
  timeout: 1m
