kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: data
provisioner: ru.yandex.s3.csi
parameters:
  csi.storage.k8s.io/controller-publish-secret-name: s3-minio-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: s3-minio-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: s3-minio-secret
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: s3-minio-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  mounter: s3fs
  bucket: data