apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-app
      image: my-image
      volumeMounts:
        - name: minio-volume
          mountPath: /data
  volumes:
    - name: minio-volume
      persistentVolumeClaim:
        claimName: minio-pvc